### ISSUE TITLE
时间类型的数据为null的话报错

### ISSUE THREAD

**Issue by littlecc1** [sunshinelyz/mykit-db-sync#1]
Data truncation: Incorrect date value: 'null' for column 'symptoms_time' at row 3
 SQL执行出错，请检查是否存在语法错误

**Comment by binghe001** [comment]
哪种数据库呢？

**Comment by binghe001** [comment]
> 
> 
> Data truncation: Incorrect date value: 'null' for column 'symptoms_time' at row 3
> SQL执行出错，请检查是否存在语法错误

问题已经修复，详见：https://github.com/sunshinelyz/mykit-db-sync/releases/tag/0.1.1
